spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    nc: #NC数据库
      url: jdbc:oracle:thin:@localhost:1521:orcl
      username: NC65
      password: NC65
      driver-class-name: oracle.jdbc.driver.OracleDriver

    wxwb: #外协外包数据库
      url: jdbc:dm://localhost:5236/SYSDBA?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
      username: SYSDBA
      password: 1446480467lj
      driver-class-name: dm.jdbc.driver.DmDriver
