server:
  port: 8089
  
mybatis-plus:
  mapper-locations:
  #复杂的sql 可以用在接口中使用注解或者定义xml
  #- classpath:/mapper/*/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  config: classpath:logback-spring.xml
  
spring:
  profiles:
    active:
    - test

