spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    nc: #NC数据库
      url: jdbc:oracle:thin:@222.1.5.218:1521:orcl
      username: NC65TEST3
      password: NC65TEST3
      driver-class-name: oracle.jdbc.driver.OracleDriver

    wxwb: #外协外包数据库
      url: jdbc:dm://222.1.5.182:5236/JARIACECM1?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
      username: JARIACECM1
      password: jarisoft11
      driver-class-name: dm.jdbc.driver.DmDriver
